//select '{codigo: ''' || codigoagregador || ''', descricao: ''' || descricao || ''', selecionado: false},'
//from agregador




export function obterTodosAgregadores(){
        return [
                {codigo: '070', descricao: 'Metrô de Natal, João Pessoa e Maceió', selecionado: false},
                {codigo: '071', descricao: 'PAC Equipamentos - Apoio à Aquisição de Equipamentos', selecionado: false},
                {codigo: '072', descricao: 'Plano Brasil sem Miséria', selecionado: false},
                {codigo: '073', descricao: 'RIO+20', selecionado: false},
                {codigo: '074', descricao: 'Índice de Gestão Descentralizada do Bolsa Família - IGD', selecionado: false},
                {codigo: '075', descricao: 'SISFRON - Sistema Integrado de Monitoramento de Fronteiras', selecionado: false},
                {codigo: '076', descricao: 'Aviação Civil', selecionado: false},
                {codigo: '077', descricao: 'Copa do Mundo 2014', selecionado: false},
                {codigo: '078', descricao: 'OIimpíadas 2016', selecionado: false},
                {codigo: '079', descricao: 'Grandes Eventos', selecionado: false},
                {codigo: '080', descricao: 'Desenvolvimento do Setor de Comércio e Serviços', selecionado: false},
                {codigo: '081', descricao: 'Sistemas Estruturantes e Corporativos', selecionado: false},
                {codigo: '082', descricao: 'Construção e Reforma de Edifícios', selecionado: false},
                {codigo: '083', descricao: 'Estatuto de Defesa do Torcedor e Apoio ao Desenvolvimento do Futebol', selecionado: false},
                {codigo: '084', descricao: 'Reaparelhamento Marinha - PROSUB - Programa de Desenvolvimento de Submarinos', selecionado: false},
                {codigo: '085', descricao: 'Hidrovia do Rio Tietê', selecionado: false},
                {codigo: '086', descricao: 'Fundo Social', selecionado: false},
                {codigo: '087', descricao: 'Remuneração de Agentes Financeiros', selecionado: false},
                {codigo: '088', descricao: 'Programas de Proteção', selecionado: false},
                {codigo: '089', descricao: 'Infraestrutura para Pesca e Aquicultura', selecionado: false},
                {codigo: '090', descricao: 'Equalização de Taxas do Profrota', selecionado: false},
                {codigo: '091', descricao: 'GAP do PAC', selecionado: false},
                {codigo: '092', descricao: 'Estatísticas Econômicas - IBGE', selecionado: false},
                {codigo: '093', descricao: 'Subvenção ao Preço do Óleo Díesel', selecionado: false},
                {codigo: '094', descricao: 'Fiscalização/Monitoramento da Pesca e Aquicultura', selecionado: false},
                {codigo: '095', descricao: 'Sanidade e Qualidade da Produção Pesqueira e Aquícola', selecionado: false},
                {codigo: '096', descricao: 'Gestão, Logística e Governança', selecionado: false},
                {codigo: '097', descricao: 'Gestão do Orçamento', selecionado: false},
                {codigo: '098', descricao: 'Gestão do Patrimônio Imobiliário da União', selecionado: false},
                {codigo: '099', descricao: 'Gestão das Relações de Trabalho', selecionado: false},
                {codigo: '100', descricao: 'Gestão de Riscos e Respostas a Desastres Naturais', selecionado: false},
                {codigo: '101', descricao: 'Atividades Censitárias', selecionado: false},
                {codigo: '102', descricao: 'Unidades Móveis de Atendimento', selecionado: false},
                {codigo: '103', descricao: 'Pesquisas Econômicas Aplicadas - IPEA', selecionado: false},
                {codigo: '104', descricao: 'PNAGE', selecionado: false},
                {codigo: '105', descricao: 'PROMOEX', selecionado: false},
                {codigo: '106', descricao: 'Ampliação do Complexo de Anexos do Palácio do Planalto', selecionado: false},
                {codigo: '107', descricao: 'SAE - Secretaria de Assuntos Estratégicos', selecionado: false},
                {codigo: '108', descricao: 'FUNPEN - Fundo Penitenciário Nacional', selecionado: false},
                {codigo: '109', descricao: 'Atenção Básica', selecionado: false},
                {codigo: '110', descricao: 'Crack, é Possível Vencer', selecionado: false},
                {codigo: '111', descricao: 'Criminalidade Violenta', selecionado: false},
                {codigo: '112', descricao: 'Atenção Especializada', selecionado: false},
                {codigo: '113', descricao: 'Sinesp - Sist. Nac. de Info. de Segurança Pública, Prisionais e sobre Drogas', selecionado: false},
                {codigo: '114', descricao: 'Violência no Trânsito', selecionado: false},
                {codigo: '115', descricao: 'CEMADEN - Centro Nacional de Monitoramento e Alerta de Desastres Naturais', selecionado: false},
                {codigo: '116', descricao: 'CSF - Ciência sem Fronteiras', selecionado: false},
                {codigo: '117', descricao: 'Territórios da Cidadania', selecionado: false},
                {codigo: '118', descricao: 'Viver sem Limite', selecionado: false},
                {codigo: '119', descricao: 'INB - Indústrias Nucleares do Brasil', selecionado: false},
                {codigo: '120', descricao: 'NUCLEP - Nuclebrás Equipamentos Pesados', selecionado: false},
                {codigo: '121', descricao: 'Procuradoria-Geral da Fazenda Nacional', selecionado: false},
                {codigo: '122', descricao: 'Juventude', selecionado: false},
                {codigo: '123', descricao: 'Receita Federal do Brasil', selecionado: false},
                {codigo: '124', descricao: 'OS - Organizações Sociais', selecionado: false},
                {codigo: '125', descricao: 'Banco Central do Brasil', selecionado: false},
                {codigo: '126', descricao: 'Contribuição à Fundação Getúlio Vargas', selecionado: false},
                {codigo: '127', descricao: 'Secretaria do Tesouro Nacional', selecionado: false},
                {codigo: '128', descricao: 'Comissão de Valores Mobiliários e Superintendência de Seguros Privados', selecionado: false},
                {codigo: '129', descricao: 'Modernização da Receita Federal - PPI', selecionado: false},
                {codigo: '130', descricao: 'Receita Previdenciária', selecionado: false},
                {codigo: '131', descricao: 'Administração direta - Fomento à Pesquisa e Inclusão Digital', selecionado: false},
                {codigo: '132', descricao: 'SINTEGRA', selecionado: false},
                {codigo: '133', descricao: 'Despesa Administrativa da Administração Direta', selecionado: false},
                {codigo: '134', descricao: 'Alcântara - Implantação do Centro Espacial de Alcântara', selecionado: false},
                {codigo: '135', descricao: 'Aquisição de terreno para CGU', selecionado: false},
                {codigo: '136', descricao: 'Movimentação de Militares Aeronáutica', selecionado: false},
                {codigo: '137', descricao: 'Movimentação de Militares Exército', selecionado: false},
                {codigo: '138', descricao: 'Movimentação de Militares Marinha', selecionado: false},
                {codigo: '139', descricao: 'Organizações Militares Aeronáutica', selecionado: false},
                {codigo: '140', descricao: 'Organizações Militares Exército', selecionado: false},
                {codigo: '141', descricao: 'Organizações Militares Marinha', selecionado: false},
                {codigo: '142', descricao: 'Reaparelhamento Aeronáutica - Desenvolvimento KC-X', selecionado: false},
                {codigo: '143', descricao: 'Casa da Mulher Brasileira', selecionado: false},
                {codigo: '144', descricao: 'Defesa Agropecuária (reforma dos LANAGROS)', selecionado: false},
                {codigo: '145', descricao: 'Call Center', selecionado: false},
                {codigo: '146', descricao: 'SECOM (exceto Publicidade Institucional)', selecionado: false},
                {codigo: '147', descricao: 'Comissão da Verdade', selecionado: false},
                {codigo: '148', descricao: 'Fundo de Estabilidade do Seguro Rural - FESR', selecionado: false},
                {codigo: '149', descricao: 'Garantia à Exportação', selecionado: false},
                {codigo: '150', descricao: 'Aquisição e Construção de Imóveis', selecionado: false},
                {codigo: '151', descricao: 'Promoção do Turismo Interno', selecionado: false},
                {codigo: '152', descricao: 'Prodetur', selecionado: false},
                {codigo: '153', descricao: 'Embratur', selecionado: false},
                {codigo: '154', descricao: 'Advocacia Pública Eletrônica', selecionado: false},
                {codigo: '155', descricao: 'Fungetur', selecionado: false},
                {codigo: '156', descricao: 'Gestão da Política de Turismo', selecionado: false},
                {codigo: '157', descricao: 'Brasil Protege', selecionado: false},
                {codigo: '158', descricao: 'Dessalinização - BSM', selecionado: false},
                {codigo: '159', descricao: 'Aviação Civil - Aviação Regional', selecionado: false},
                {codigo: '160', descricao: 'PUC (Infraero)', selecionado: false},
                {codigo: '161', descricao: 'PUC (Docas)', selecionado: false},
                {codigo: '162', descricao: 'Bolsa Verde - BSM', selecionado: false},
                {codigo: '163', descricao: 'PUP - Publicidade de Utilidade Pública', selecionado: false},
                {codigo: '164', descricao: 'PRONATEC', selecionado: false},
                {codigo: '165', descricao: 'Exames e Avaliações da Educação Básica', selecionado: false},
                {codigo: '166', descricao: 'Remuneração Bancos - Previdência', selecionado: false},
                {codigo: '167', descricao: 'Remuneração Bancos - Outros', selecionado: false},
                {codigo: '168', descricao: 'Pesquisa e Desenvolvimento nas Organizações Sociais', selecionado: false},
                {codigo: '169', descricao: 'Funcionamento e Manutenção de Instituições Federais de Educação Profissional e Tecnológica', selecionado: false},
                {codigo: '170', descricao: 'Funcionamento e Manutenção de Instituições Federais de Ensino Superior', selecionado: false},
                {codigo: '171', descricao: 'Benefícios aos Extintos Territórios', selecionado: false},
                {codigo: '172', descricao: 'Transferências aos Demais Entes Públicos', selecionado: false},
                {codigo: '173', descricao: 'Funcionamento e Manutenção de Hospitais Universitários', selecionado: false},
                {codigo: '174', descricao: 'Polícia Federal - Passaportes', selecionado: false},
                {codigo: '175', descricao: 'Esporte, Lazer e Inclusão Social', selecionado: false},
                {codigo: '176', descricao: 'Funcionamento das Agências de Trabalho e Emprego', selecionado: false},
                {codigo: '177', descricao: 'Autoridade Pública Olímpica - APO', selecionado: false},
                {codigo: '178', descricao: 'Encargos do Fundo da Marinha Mercante', selecionado: false},
                {codigo: '179', descricao: 'Transferências à CBC e à FENACLUBES', selecionado: false},
                {codigo: '180', descricao: 'Qualificação do SUS', selecionado: false},
                {codigo: '181', descricao: 'Despesa Administrativa', selecionado: false},
                {codigo: '182', descricao: 'Rede Cegonha', selecionado: false},
                {codigo: '183', descricao: 'Atenção Psicossocial', selecionado: false},
                {codigo: '184', descricao: 'Urgência e Emergência', selecionado: false},
                {codigo: '185', descricao: 'Regulação em Saúde Suplementar', selecionado: false},
                {codigo: '186', descricao: 'Fardamento Exército', selecionado: false},
                {codigo: '187', descricao: 'Fardamento Marinha', selecionado: false},
                {codigo: '188', descricao: 'Fardamento Aeronáutica', selecionado: false},
                {codigo: '189', descricao: 'Alimentação de Militares Exército', selecionado: false},
                {codigo: '190', descricao: 'Escola de Administração Fazendária', selecionado: false},
                {codigo: '191', descricao: 'Alimentação de Militares Marinha', selecionado: false},
                {codigo: '192', descricao: 'Alimentação de Militares Aeronáutica', selecionado: false},
                {codigo: '193', descricao: 'Cadastro Ambiental Rural - CAR', selecionado: false},
                {codigo: '194', descricao: 'Projeto de Assistência Técnica aos Setores de Energia e Mineral - META', selecionado: false},
                {codigo: '195', descricao: 'Regularização Fundiária Urbana (Papel Passado)', selecionado: false},
                {codigo: '196', descricao: 'Reaparelhamento Exército - Blindados Guarani', selecionado: false},
                {codigo: '197', descricao: 'Reaparelhamento Exército - ASTROS 2020 - Sistema de Defesa Estratégico', selecionado: false},
                {codigo: '198', descricao: 'Alimentação de Militares Administração Central', selecionado: false},
                {codigo: '199', descricao: 'Bolsas Educação Especial Aeronáutica', selecionado: false},
                {codigo: '200', descricao: 'Bolsas Educação Especial Exército', selecionado: false},
                {codigo: '201', descricao: 'Pesca e Aquicultura', selecionado: false},
                {codigo: '202', descricao: 'Arquivo Nacional', selecionado: false},
                {codigo: '203', descricao: 'Ações de Controle', selecionado: false},
                {codigo: '204', descricao: 'Tecnologia Adm. Central - SGDC - Satélite Geoestacionário de Defesa e Comunicação Estratégico', selecionado: false},
                {codigo: '205', descricao: 'Defesa Jurídica da União', selecionado: false},
                {codigo: '206', descricao: 'Direitos Humanos', selecionado: false},
                {codigo: '207', descricao: 'Relações Institucionais e Conselhos', selecionado: false},
                {codigo: '208', descricao: 'Igualdade Racial', selecionado: false},
                {codigo: '209', descricao: 'Imprensa Nacional', selecionado: false},
                {codigo: '210', descricao: 'Segurança Institucional', selecionado: false},
                {codigo: '211', descricao: 'Política Antidrogas', selecionado: false},
                {codigo: '212', descricao: 'Políticas para as Mulheres', selecionado: false},
                {codigo: '213', descricao: 'ProJovem', selecionado: false},
                {codigo: '214', descricao: 'Publicidade Institucional', selecionado: false},
                {codigo: '215', descricao: 'EBC - Empresa Brasil de Comunicação', selecionado: false},
                {codigo: '216', descricao: 'ITI - Inst. Nac. Tecnologia da Informação', selecionado: false},
                {codigo: '217', descricao: 'Vice-Presidência', selecionado: false},
                {codigo: '218', descricao: 'Apoio e Fomento à Pesquisa', selecionado: false},
                {codigo: '219', descricao: 'CNPq - Bolsas (exceto CSF)', selecionado: false},
                {codigo: '220', descricao: 'Funcionamento e Manutenção', selecionado: false},
                {codigo: '221', descricao: 'Contribuição a Organismos Internacionais - Sistema ONU', selecionado: false},
                {codigo: '222', descricao: 'Dividendos do Fundo Nacional de Desenvolvimento - FND', selecionado: false},
                {codigo: '223', descricao: 'Funcionamento e Manutenção no Exterior', selecionado: false},
                {codigo: '224', descricao: 'FNDCT - Fundo Nac. de Desenv. Científico e Tecnológico (exceto CSF e OS)', selecionado: false},
                {codigo: '225', descricao: 'Administração direta - Unidades de Pesquisa', selecionado: false},
                {codigo: '226', descricao: 'P & D para Inclusão Social', selecionado: false},
                {codigo: '227', descricao: 'P & D para o Meio Ambiente', selecionado: false},
                {codigo: '228', descricao: 'AEB - Agência Espacial Brasileira', selecionado: false},
                {codigo: '229', descricao: 'CNEN - Comissão Nacional de Energia Nuclear', selecionado: false},
                {codigo: '230', descricao: 'Ampliação das Instalações da Polícia Federal', selecionado: false},
                {codigo: '231', descricao: 'Ampliação das Instalações da Polícia Rodoviária Federal', selecionado: false},
                {codigo: '232', descricao: 'Defensoria Pública', selecionado: false},
                {codigo: '233', descricao: 'Fundo Nacional de Segurança Pública', selecionado: false},
                {codigo: '234', descricao: 'Polícia Federal - Segurança Pública', selecionado: false},
                {codigo: '235', descricao: 'Polícia Rodoviária Federal - Segurança Pública', selecionado: false},
                {codigo: '236', descricao: 'Modernização da Polícia Federal (Promotec / Pró-Amazônia)', selecionado: false},
                {codigo: '237', descricao: 'ENAFRON - Estratégia Nacional de Segurança Pública nas Fronteiras', selecionado: false},
                {codigo: '238', descricao: 'Polícia Federal - Manutenção Administrativa', selecionado: false},
                {codigo: '239', descricao: 'FUNPEN -Não Usar XXXXX Penitenciárias XXXXXXXXXXXXXXXX Federais_Não Usar', selecionado: false},
                {codigo: '240', descricao: 'FUNAI - Fundação Nacional do Índio', selecionado: false},
                {codigo: '241', descricao: 'Polícia Rodoviária Federal - Manutenção Administrativa', selecionado: false},
                {codigo: '242', descricao: 'Demais Ações Diplomáticas no Exterior', selecionado: false},
                {codigo: '243', descricao: 'Ações Diplomáticas no País', selecionado: false},
                {codigo: '244', descricao: 'Adestramento Administração Central - Defesa', selecionado: false},
                {codigo: '245', descricao: 'Adestramento Aeronáutica', selecionado: false},
                {codigo: '246', descricao: 'Adestramento Exército', selecionado: false},
                {codigo: '247', descricao: 'Adestramento Marinha', selecionado: false},
                {codigo: '248', descricao: 'ANAC - Agência Nacional de Aviação Civil', selecionado: false},
                {codigo: '249', descricao: 'FUNAI - Manutenção Administrativa', selecionado: false},
                {codigo: '250', descricao: 'Manutenção Administrativa - Demais', selecionado: false},
                {codigo: '251', descricao: 'Manutenção ITI', selecionado: false},
                {codigo: '252', descricao: 'EBC - Manutenção', selecionado: false},
                {codigo: '253', descricao: 'Calha Norte', selecionado: false},
                {codigo: '254', descricao: 'SISCEAB - Controle do Espaço Aéreo', selecionado: false},
                {codigo: '255', descricao: 'Controle e Fiscalização Exército', selecionado: false},
                {codigo: '256', descricao: 'Controle e Fiscalização Marinha', selecionado: false},
                {codigo: '257', descricao: 'Demais Administração Central', selecionado: false},
                {codigo: '258', descricao: 'Demais Aeronáutica', selecionado: false},
                {codigo: '259', descricao: 'Demais Exército', selecionado: false},
                {codigo: '260', descricao: 'Demais Marinha', selecionado: false},
                {codigo: '261', descricao: 'Ensino Administração Central', selecionado: false},
                {codigo: '262', descricao: 'Ensino Aeronáutica', selecionado: false},
                {codigo: '263', descricao: 'Ensino Exército', selecionado: false},
                {codigo: '264', descricao: 'Ensino Marinha', selecionado: false},
                {codigo: '265', descricao: 'Produção de Fármacos Aeronáutica', selecionado: false},
                {codigo: '266', descricao: 'Produção de Fármacos Exército', selecionado: false},
                {codigo: '267', descricao: 'Produção de Fármacos Marinha', selecionado: false},
                {codigo: '268', descricao: 'Funcionamento e Manutenção Administração Central', selecionado: false},
                {codigo: '269', descricao: 'Funcionamento e Manutenção Aeronáutica', selecionado: false},
                {codigo: '270', descricao: 'Funcionamento e Manutenção Exército', selecionado: false},
                {codigo: '271', descricao: 'Funcionamento e Manutenção Marinha', selecionado: false},
                {codigo: '272', descricao: 'Obtenção e Modernização de Meios Aeronáutica', selecionado: false},
                {codigo: '273', descricao: 'Obtenção e Modernização de Meios Exército', selecionado: false},
                {codigo: '274', descricao: 'Obtenção e Modernização de Meios Marinha', selecionado: false},
                {codigo: '275', descricao: 'CADE - Conselho Administrativo de Defesa Econômica', selecionado: false},
                {codigo: '276', descricao: 'Esforço Aéreo (Combustíveis e Material Aeronáutico)', selecionado: false},
                {codigo: '277', descricao: 'Soldado Cidadão', selecionado: false},
                {codigo: '278', descricao: 'Convênios do Comando do Exército', selecionado: false},
                {codigo: '279', descricao: 'IMBEL - Indústria de Material Bélico do Brasil', selecionado: false},
                {codigo: '280', descricao: 'PROANTAR - Programa Antártico Brasileiro', selecionado: false},
                {codigo: '281', descricao: 'PROFAB', selecionado: false},
                {codigo: '282', descricao: 'Tecnologia Administração Central', selecionado: false},
                {codigo: '283', descricao: 'Tecnologia Aeronáutica', selecionado: false},
                {codigo: '284', descricao: 'Tecnologia Exército', selecionado: false},
                {codigo: '285', descricao: 'Tecnologia Marinha', selecionado: false},
                {codigo: '286', descricao: 'Investimentos Aeroportuários', selecionado: false},
                {codigo: '287', descricao: 'SIPAM - Sistema de Proteção da Amazônia', selecionado: false},
                {codigo: '288', descricao: 'Gestão Aeroportuária', selecionado: false},
                {codigo: '289', descricao: 'CEITEC - Centro Nacional de Tecnologia Eletrônica Avançada', selecionado: false},
                {codigo: '290', descricao: 'CBERS', selecionado: false},
                {codigo: '291', descricao: 'Alcântara Cyclone Space', selecionado: false},
                {codigo: '292', descricao: 'Veiculos Lançadores de Satelites - VLS', selecionado: false},
                {codigo: '293', descricao: 'Estudo e Pesquisa', selecionado: false},
                {codigo: '294', descricao: 'SENASP - Segurança Pública', selecionado: false},
                {codigo: '295', descricao: 'Hanseníase', selecionado: false},
                {codigo: '296', descricao: 'Jogos Mundiais Militares', selecionado: false},
                {codigo: '297', descricao: 'Pré-Sal Petróleo S.A. - PPSA', selecionado: false},
                {codigo: '298', descricao: 'Fundo Soberano do Brasil', selecionado: false},
                {codigo: '299', descricao: 'Administração Direta (exceto Segurança Pública - SENASP)', selecionado: false},
                {codigo: '300', descricao: 'Minha Casa, Minha Vida - PMCMV', selecionado: false},
                {codigo: '301', descricao: 'Defesa Judicial', selecionado: false},
                {codigo: '302', descricao: 'Preparação de Atletas', selecionado: false},
                {codigo: '303', descricao: 'CGU - Obras', selecionado: false},
                {codigo: '304', descricao: 'ATER para Agricultura Patronal', selecionado: false},
                {codigo: '305', descricao: 'Ponte São Borja - Santo Tomé', selecionado: false},
                {codigo: '306', descricao: 'Escola Nacional da Administração Pública', selecionado: false},
                {codigo: '307', descricao: 'Fomento ao Setor Agropecuário', selecionado: false},
                {codigo: '308', descricao: 'Funcionamento de Órgãos Colegiados de Previdência', selecionado: false},
                {codigo: '309', descricao: 'Regimes Próprios de Previdência', selecionado: false},
                {codigo: '310', descricao: 'Controles Internos, Gestão de Riscos e Combate às Fraudes na Área de Previdência Social', selecionado: false},
                {codigo: '311', descricao: 'SGDC - Satélite Geostacionário de Defesa e Comunicação (PUC Telebrás)', selecionado: false},
                {codigo: '312', descricao: 'Obtenção e Modernização de Meios Administração Central', selecionado: false},
                {codigo: '313', descricao: 'SGDC - Satélite Geostacionário de Defesa e Comunicação - (Transferência de Tecnologia/AEB)', selecionado: false},
                {codigo: '314', descricao: 'FNDCT - Programa Nacional de Plataformas do Conhecimento', selecionado: false},
                {codigo: '315', descricao: 'ANCINE - Agência Nacional do Cinema', selecionado: false},
                {codigo: '316', descricao: 'Subvenção para a Aviação Civil Regional', selecionado: false},
                {codigo: '317', descricao: 'Hospital das Forças Armadas - HFA', selecionado: false},
                {codigo: '318', descricao: 'FINEP - Participação da União no Capital', selecionado: false},
                {codigo: '319', descricao: 'Cédulas e Moedas', selecionado: false},
                {codigo: '320', descricao: 'Reaparelhamento Aeronáutica - Aquisição de Caças FX-2', selecionado: false},
                {codigo: '321', descricao: 'Água para Todos - BSM', selecionado: false},
                {codigo: '322', descricao: 'Terminais Pesqueiros Públicos - TPP', selecionado: false},
                {codigo: '323', descricao: 'Manutenção da Casa da Mulher Brasileira', selecionado: false},
                {codigo: '324', descricao: 'Inclusão Produtiva', selecionado: false},
                {codigo: '325', descricao: 'Representações Diplomáticas', selecionado: false},
                {codigo: '326', descricao: 'Cabo Submarino (PUC Telebrás)', selecionado: false},
                {codigo: '327', descricao: 'PNBL/Infraestrutura de Comunicações de Dados (PUC Telebrás)', selecionado: false},
                {codigo: '328', descricao: 'Centro de Iniciação ao Esporte - CIE', selecionado: false},
                {codigo: '329', descricao: 'Infraestrutura esportiva (E)', selecionado: false},
                {codigo: '330', descricao: 'Construção de Unidades Básicas de Saúde - UBS', selecionado: false},
                {codigo: '331', descricao: 'Implantação, Construção e Ampliação de Unidades de Pronto Atendimento - UPA', selecionado: false},
                {codigo: '332', descricao: 'Ferrovia Transnordestina', selecionado: false},
                {codigo: '333', descricao: 'Ferrovia FNS - Açailândia/MA - Palmas/TO', selecionado: false},
                {codigo: '334', descricao: 'Ferrovia FNS - Palmas/TO - Anápolis/GO', selecionado: false},
                {codigo: '335', descricao: 'Ferrovia FNS - Ouroverde/GO - Estrela DOeste/SP', selecionado: false},
                {codigo: '336', descricao: 'Manutenção e Operação da Malha Ferroviária', selecionado: false},
                {codigo: '337', descricao: 'Ferrovia FNS - Recuperação de Áreas Degradadas', selecionado: false},
                {codigo: '338', descricao: 'Ferrovia FIOL - Ilhéus/BA - Caetité/BA', selecionado: false},
                {codigo: '339', descricao: 'Ferrovia FIOL - Caetité/BA - Barreiras/BA', selecionado: false},
                {codigo: '340', descricao: 'Projetos, Estudos e Pesquisas', selecionado: false},
                {codigo: '341', descricao: 'Fiscalização e Regulação', selecionado: false},
                {codigo: '342', descricao: 'Reaparelhamento Aeronáutica - Aquisição do Cargueiro Tático Militar KC-390', selecionado: false},
                {codigo: '343', descricao: 'Reaparelhamento Aeronáutica - PAC Equipamentos', selecionado: false},
                {codigo: '344', descricao: 'Reaparelhamento Exército - PAC Equipamentos', selecionado: false},
                {codigo: '345', descricao: 'Reaparelhamento Marinha - PAC Equipamentos', selecionado: false},
                {codigo: '346', descricao: 'Tecnologia Marinha - Programa Nuclear', selecionado: false},
                {codigo: '347', descricao: 'Riscos e Desastres Naturais - PAC Seca', selecionado: false},
                {codigo: '348', descricao: 'Estudos e Projetos', selecionado: false},
                {codigo: '349', descricao: 'Riscos e Desastres Naturais - PAC Cheia', selecionado: false},
                {codigo: '350', descricao: 'São Francisco/Operação', selecionado: false},
                {codigo: '351', descricao: 'Cia Docas da Bahia', selecionado: false},
                {codigo: '352', descricao: 'Cia Docas de São Paulo', selecionado: false},
                {codigo: '353', descricao: 'Cia Docas do Ceará', selecionado: false},
                {codigo: '354', descricao: 'Cia Docas do Espírito Santo', selecionado: false},
                {codigo: '355', descricao: 'Cia Docas do Pará', selecionado: false},
                {codigo: '356', descricao: 'Cia Docas do Rio de Janeiro', selecionado: false},
                {codigo: '357', descricao: 'Cia Docas do Rio Grande do Norte', selecionado: false},
                {codigo: '358', descricao: 'Dragagem', selecionado: false},
                {codigo: '359', descricao: 'Modernização Portuária (PSP e CI)', selecionado: false},
                {codigo: '360', descricao: 'Obras Diretas e Delegadas', selecionado: false},
                {codigo: '361', descricao: 'Portos Fluviais', selecionado: false},
                {codigo: '362', descricao: 'Ferrovias - Concessões', selecionado: false},
                {codigo: '363', descricao: 'Rodovias - Concessões', selecionado: false},
                {codigo: '364', descricao: 'Ferrovia Transcontinental', selecionado: false},
                {codigo: '365', descricao: 'Ferrovia FNS - Estrela DOeste - Panorama - SP', selecionado: false},
                {codigo: '366', descricao: 'Segurança nas Estradas - Peso e velocidade', selecionado: false},
                {codigo: '367', descricao: 'Aviação Civil - Aeroportos de Interesse Federal', selecionado: false},
                {codigo: '368', descricao: 'Ferrovia do Pantanal', selecionado: false},
                {codigo: '369', descricao: 'Manutenção da Administração direta', selecionado: false},
                {codigo: '370', descricao: 'SFB - Sistema Florestal Brasileiro - Manutenção', selecionado: false},
                {codigo: '371', descricao: 'JBRJ  - Instituto de Pesquisas Jardim Botânico/RJ -  Manutenção', selecionado: false},
                {codigo: '372', descricao: 'JBRJ - Instituto de Pesquisas Jardim Botânico/RJ', selecionado: false},
                {codigo: '373', descricao: 'Ferrovia FNS - Belém/PA - Açailândia/MA', selecionado: false},
                {codigo: '374', descricao: 'Agência Nacional de Mineração - Gestão do Setor Mineral', selecionado: false},
                {codigo: '375', descricao: 'ANEEL - Regulação do Setor Elétrico', selecionado: false},
                {codigo: '376', descricao: 'TRENSURB', selecionado: false},
                {codigo: '377', descricao: 'CBTU - Expansão dos Sistemas de Transporte', selecionado: false},
                {codigo: '378', descricao: 'Segurança e Educação de Trânsito', selecionado: false},
                {codigo: '379', descricao: 'Fundo Nacional de Habitação de Interesse Social - FNHIS', selecionado: false},
                {codigo: '380', descricao: 'ATER para Mobilidade no Campo - Classes C e D', selecionado: false},
                {codigo: '381', descricao: 'Política Agrícola, Redução de Riscos e Agroenergia', selecionado: false},
                {codigo: '382', descricao: 'Conferências de Políticas Públicas', selecionado: false},
                {codigo: '383', descricao: 'Indenização de Representação no Exterior Aeronáutica', selecionado: false},
                {codigo: '384', descricao: 'Indenização de Representação no Exterior Exército', selecionado: false},
                {codigo: '385', descricao: 'Indenização de Representação no Exterior Marinha', selecionado: false},
                {codigo: '386', descricao: 'Integralizações de Cotas de Organismos Multilaterais - MP', selecionado: false},
                {codigo: '387', descricao: 'Auxílio-Moradia', selecionado: false},
                {codigo: '388', descricao: 'Corredor Ferroviário do Paraná', selecionado: false},
                {codigo: '389', descricao: 'Controle de Dopagem', selecionado: false},
                {codigo: '390', descricao: 'Comunicação - PR (exceto EBC)', selecionado: false},
                {codigo: '391', descricao: 'Parcerias de Investimentos', selecionado: false},
                {codigo: '392', descricao: 'Rede Nacional de Treinamento', selecionado: false},
                {codigo: '393', descricao: 'Autódromo do Rio de Janeiro', selecionado: false},
                {codigo: '394', descricao: 'Despesas Administrativas', selecionado: false},
                {codigo: '395', descricao: 'Previdência Social', selecionado: false},
                {codigo: '396', descricao: 'Cartão Reforma', selecionado: false},
                {codigo: '397', descricao: 'GLO - Garantia da Lei e da Ordem', selecionado: false},
                {codigo: '398', descricao: 'Criança Feliz', selecionado: false},
                {codigo: '399', descricao: 'ManXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXutenção', selecionado: false},
                {codigo: '400', descricao: 'Legado Olímpico', selecionado: false},
                {codigo: '401', descricao: 'AIDS', selecionado: false},
                {codigo: '402', descricao: 'Arrecadação de Receitas Previdenciárias', selecionado: false},
                {codigo: '403', descricao: 'Atenção à Saúde de Populações Estratégicas', selecionado: false},
                {codigo: '404', descricao: 'Atenção à Saúde Indígena', selecionado: false},
                {codigo: '405', descricao: 'Atenção em Média e Alta Complexidade (MAC)', selecionado: false},
                {codigo: '406', descricao: 'Bolsa-Família', selecionado: false},
                {codigo: '407', descricao: 'Dataprev - INSS', selecionado: false},
                {codigo: '408', descricao: 'Despesas Operacionais com Benefícios', selecionado: false},
                {codigo: '409', descricao: 'Estruturação de Unidades de Saúde', selecionado: false},
                {codigo: '410', descricao: 'Farmácia Popular', selecionado: false},
                {codigo: '411', descricao: 'Fiscalização  de Obrigações Trabalhistas e de Segurança e Saúde no Trabalho', selecionado: false},
                {codigo: '412', descricao: 'Participação Social', selecionado: false},
                {codigo: '413', descricao: 'Hospitais Próprios', selecionado: false},
                {codigo: '414', descricao: 'Imunobiológicos e Vacinas', selecionado: false},
                {codigo: '415', descricao: 'Incentivos Financeiros do SUS', selecionado: false},
                {codigo: '416', descricao: 'Assistência Farmacêutica', selecionado: false},
                {codigo: '417', descricao: 'Integralização de Capital - Dataprev', selecionado: false},
                {codigo: '418', descricao: 'Integralizações de Cotas de Organismos Multilaterais - ME', selecionado: false},
                {codigo: '419', descricao: 'Participação da União no Capital de Empresas Públicas e Sociedades Anônimas', selecionado: false},
                {codigo: '420', descricao: 'Integralização de Cotas em Fundos de Natureza Privada', selecionado: false},
                {codigo: '421', descricao: 'Dataprev - Fundo de Amparo ao Trabalhador', selecionado: false},
                {codigo: '422', descricao: 'Gestão e Administração do Programa', selecionado: false},
                {codigo: '423', descricao: 'Mulheres', selecionado: false},
                {codigo: '424', descricao: 'Perícia Médica e Reabilitação Profissional', selecionado: false},
                {codigo: '425', descricao: 'Programa de Aquisição de Alimentos - PAA', selecionado: false},
                {codigo: '426', descricao: 'Programa de Erradicação do Trabalho Infantil', selecionado: false},
                {codigo: '427', descricao: 'Recadastramento Previdenciário', selecionado: false},
                {codigo: '428', descricao: 'Modernização e Instalação das Agências do INSS', selecionado: false},
                {codigo: '429', descricao: 'Remuneração dos Agentes Pagadores', selecionado: false},
                {codigo: '430', descricao: 'Construção de Corvetas (PUC EMGEPRON)', selecionado: false},
                {codigo: '431', descricao: 'Segurança Alimentar', selecionado: false},
                {codigo: '432', descricao: 'Sentinela', selecionado: false},
                {codigo: '433', descricao: 'Sistema Único de Assistência Social - SUAS', selecionado: false},
                {codigo: '434', descricao: 'Vigilância Sanitária, Epidemiológica e Ambiental', selecionado: false},
                {codigo: '435', descricao: 'Apoio Operacional ao Pagamento do Seguro-Desemprego e do Abono Salarial', selecionado: false},
                {codigo: '436', descricao: 'Economia Solidária', selecionado: false},
                {codigo: '437', descricao: 'Reserva para Participação da União no Capital de Empresas Estatais', selecionado: false},
                {codigo: '438', descricao: 'Fundacentro', selecionado: false},
                {codigo: '439', descricao: 'PAC - Estudos de Investimentos em Infraestrutura', selecionado: false},
                {codigo: '440', descricao: 'Primeiro Emprego', selecionado: false},
                {codigo: '441', descricao: 'Qualificação Social e Profissional', selecionado: false},
                {codigo: '442', descricao: 'Registros Públicos na Área do trabalho', selecionado: false},
                {codigo: '443', descricao: 'Sistema Nacional de Emprego (SINE)', selecionado: false},
                {codigo: '444', descricao: 'Jogos Pan e Para Pan-Americanos de 2007', selecionado: false},
                {codigo: '445', descricao: 'Apoio e Fomento a Projetos Culturais', selecionado: false},
                {codigo: '446', descricao: 'Concessão de Bolsas, Prêmios e Capacitação de Agentes Culturais', selecionado: false},
                {codigo: '447', descricao: 'Contribuição a Entidades Nacionais', selecionado: false},
                {codigo: '448', descricao: 'Cultura Afro-Brasileira', selecionado: false},
                {codigo: '449', descricao: 'Funcionamento de Espaços Culturais', selecionado: false},
                {codigo: '450', descricao: 'Gerenciamento e Consolidação de Informações Culturais', selecionado: false},
                {codigo: '451', descricao: 'Identificação e Preservação de Bens Culturais de Natureza Material e Imaterial', selecionado: false},
                {codigo: '452', descricao: 'Implantação/Modernização de Espaços Culturais', selecionado: false},
                {codigo: '453', descricao: 'Cidades Históricas', selecionado: false},
                {codigo: '454', descricao: 'Cultura Viva', selecionado: false},
                {codigo: '455', descricao: 'Produção e Difusão Cultural', selecionado: false},
                {codigo: '456', descricao: 'Implantação e Modernização de Núcleos de Esporte', selecionado: false},
                {codigo: '457', descricao: 'Participação da Delegação Brasileira em Competições Nacionais e Internacionais', selecionado: false},
                {codigo: '458', descricao: 'Pintando a Liberdade e a Cidadania - Produção de Material Esportivo', selecionado: false},
                {codigo: '459', descricao: 'Promoção do Esporte e de Outros Eventos Esportivos', selecionado: false},
                {codigo: '460', descricao: 'Funcionamento de Outros Núcleos de Esporte', selecionado: false},
                {codigo: '461', descricao: 'Segundo Tempo', selecionado: false},
                {codigo: '462', descricao: 'Bolsa Atleta', selecionado: false},
                {codigo: '463', descricao: 'Bolsas CAPES/FNDE', selecionado: false},
                {codigo: '464', descricao: 'Alimentação Escolar', selecionado: false},
                {codigo: '465', descricao: 'Programa de Melhoria e Expansão do Ensino Médio - Promed', selecionado: false},
                {codigo: '466', descricao: 'Alfabetização e Educação de Jovens e Adultos', selecionado: false},
                {codigo: '467', descricao: 'Casa da Moeda do Brasil', selecionado: false},
                {codigo: '468', descricao: 'Formação e Capacitação de Profissionais da Educação Básica', selecionado: false},
                {codigo: '469', descricao: 'Expansão do Ensino Profissional', selecionado: false},
                {codigo: '470', descricao: 'Livro Didático', selecionado: false},
                {codigo: '471', descricao: 'Desenvolvimento da Educação Básica', selecionado: false},
                {codigo: '472', descricao: 'Reestruturação e Expansão do Ensino Superior', selecionado: false},
                {codigo: '473', descricao: 'Fundescola', selecionado: false},
                {codigo: '474', descricao: 'Estatísticas e Avaliações Educacionais', selecionado: false},
                {codigo: '475', descricao: 'Desenvolvimento da Educação Especial', selecionado: false},
                {codigo: '476', descricao: 'Expansão do Ensino Superior', selecionado: false},
                {codigo: '477', descricao: 'Reestruturação e Implantação de Hospitais Universitários', selecionado: false},
                {codigo: '478', descricao: 'Reestruturação e Expansão da Educação Profissional', selecionado: false},
                {codigo: '479', descricao: 'Pesquisa Científica e Tecnologia em Saúde', selecionado: false},
                {codigo: '480', descricao: 'Educação Permanente dos Profissionais do SUS', selecionado: false},
                {codigo: '481', descricao: 'Atenção à Saúde Bucal', selecionado: false},
                {codigo: '482', descricao: 'Hospital Sarah Kubitschek', selecionado: false},
                {codigo: '483', descricao: 'SAMU - Serviço de Atendimento Móvel de Urgência', selecionado: false},
                {codigo: '484', descricao: 'Assistência emergencial e acolhimento humanitário', selecionado: false},
                {codigo: '485', descricao: 'Funcionamento das Agências do INSS', selecionado: false},
                {codigo: '486', descricao: 'Funcionamento e Manutenção de Instituições Federais de Educação Básica', selecionado: false},
                {codigo: '487', descricao: 'Desenvolvimento da Educação Especial na Rede Federal', selecionado: false},
                {codigo: '488', descricao: 'Transferências para Educação Profissional', selecionado: false},
                {codigo: '489', descricao: 'Transferências para o Ensino Superior', selecionado: false},
                {codigo: '490', descricao: 'Eventos Culturais no Exterior', selecionado: false},
                {codigo: '491', descricao: 'Museus', selecionado: false},
                {codigo: '492', descricao: 'Bibliotecas - Instalação/Modernização', selecionado: false},
                {codigo: '493', descricao: 'Proinfo', selecionado: false},
                {codigo: '494', descricao: 'Creches, Quadras e Infraestrutura para Escolas', selecionado: false},
                {codigo: '495', descricao: 'Economia da Cultura', selecionado: false},
                {codigo: '496', descricao: 'TV Pública', selecionado: false},
                {codigo: '497', descricao: 'Fundo Setorial do Audiovisual', selecionado: false},
                {codigo: '498', descricao: 'Dinheiro Direto na Escola', selecionado: false},
                {codigo: '499', descricao: 'Ferrovia FNS', selecionado: false},
                {codigo: '500', descricao: 'REUNI', selecionado: false},
                {codigo: '501', descricao: 'Transporte Escolar', selecionado: false},
                {codigo: '502', descricao: 'Aquisição de Títulos do Tesouro Nacional', selecionado: false},
                {codigo: '503', descricao: 'Fundo de Garantia às Exportações', selecionado: false},
                {codigo: '504', descricao: 'Cadastro de sinistros - FUNDHAB', selecionado: false},
                {codigo: '505', descricao: 'Crédito Educativo a Estudantes Carentes', selecionado: false},
                {codigo: '506', descricao: 'Concessão de Crédito - Banco da Terra', selecionado: false},
                {codigo: '507', descricao: 'Concessão de Crédito - Fundo de Terras', selecionado: false},
                {codigo: '508', descricao: 'Concessão de Crédito às Famílias Assentadas', selecionado: false},
                {codigo: '509', descricao: 'Concessão de Empréstimos', selecionado: false},
                {codigo: '510', descricao: 'Financiamento a Empreendimentos Culturais', selecionado: false},
                {codigo: '511', descricao: 'Financiamento a Estudantes', selecionado: false},
                {codigo: '512', descricao: 'FIES', selecionado: false},
                {codigo: '513', descricao: 'Financiamento a Pequenas e Médias Empresas', selecionado: false},
                {codigo: '514', descricao: 'Financiamento de Desenvolvimento de Tecnologias', selecionado: false},
                {codigo: '515', descricao: 'Financiamento do BNDES ao Setor Elétrico', selecionado: false},
                {codigo: '516', descricao: 'Financiamento a setores Produtivos', selecionado: false},
                {codigo: '517', descricao: 'Infraestrutura Turística Nacional', selecionado: false},
                {codigo: '518', descricao: 'Financiamento dos Projetos do Setor Produtivo', selecionado: false},
                {codigo: '519', descricao: 'Reserva de Contingência Financeira', selecionado: false},
                {codigo: '520', descricao: 'Pessoal - Despesas Financeiras', selecionado: false},
                {codigo: '521', descricao: 'Ajuste Fiscal dos Estados', selecionado: false},
                {codigo: '522', descricao: 'Aquisição de Terreno - Marinha', selecionado: false},
                {codigo: '523', descricao: 'Formação de Estoques', selecionado: false},
                {codigo: '524', descricao: 'Remuneração de Agentes Financeiros - FCVS', selecionado: false},
                {codigo: '525', descricao: 'Financiamento BNDES', selecionado: false},
                {codigo: '526', descricao: 'Ferrovia FIOL', selecionado: false},
                {codigo: '527', descricao: 'Formulação e Implementação de Políticas Públicas Ambientais', selecionado: false},
                {codigo: '528', descricao: 'FNMA - Fundo Nacional de Meio Ambiente', selecionado: false},
                {codigo: '529', descricao: 'CODEBAR - Companhia de Desenvolvimento de Barcarena', selecionado: false},
                {codigo: '530', descricao: 'Extinção do Fundo Nacional de Desenvolvimento (FND)', selecionado: false},
                {codigo: '531', descricao: 'Apoio Financeiro aos Municípios - MP nº 815/2017', selecionado: false},
                {codigo: '532', descricao: 'Intervenção Federal no Estado do Rio de Janeiro', selecionado: false},
                {codigo: '533', descricao: 'Esporte de Alto Rendimento', selecionado: false},
                {codigo: '534', descricao: 'PUC - Empresa Brasileira de Correios e Telégrafos (ECT)', selecionado: false},
                {codigo: '535', descricao: 'Fundo de Defesa de Direitos Difusos', selecionado: false},
                {codigo: '536', descricao: 'Encargos Decorrentes da Extinção de Entidades Vinculadas ao MCTIC', selecionado: false},
                {codigo: '537', descricao: 'Extinção de Entidades', selecionado: false},
                {codigo: '538', descricao: 'Obtenção de Navio de Apoio Antártico (PUC EMGEPRON)', selecionado: false},
                {codigo: '539', descricao: 'Intervenção Federal no Estado de Roraima', selecionado: false},
                {codigo: '540', descricao: 'Demandas não Detalhadas', selecionado: false},
                {codigo: '541', descricao: 'Desenvolvimento do Ensino  Superior', selecionado: false},
                {codigo: '542', descricao: 'Assistência ao Estudante do Ensino Superior e da Educação Profissional e Tecnológica', selecionado: false},
                {codigo: '543', descricao: 'Desenvolvimento da Educação Profissional e Tecnológica', selecionado: false},
                {codigo: '544', descricao: 'Pessoal Inativo', selecionado: false},
                {codigo: '545', descricao: 'Regularização fundiária de Terras Indígenas', selecionado: false},
                {codigo: '601', descricao: 'ANEEL', selecionado: false},
                {codigo: '602', descricao: 'ANP', selecionado: false},
                {codigo: '603', descricao: 'Agência Nacional de Mineração', selecionado: false},
                {codigo: '604', descricao: 'CPRM', selecionado: false},
                {codigo: '605', descricao: 'Luz para Todos', selecionado: false},
                {codigo: '606', descricao: 'EPE', selecionado: false},
                {codigo: '623', descricao: 'Planejamento e Fomento em Energia e Mineração', selecionado: false},
                {codigo: '624', descricao: 'Bônus a Consumidores de Energia Elétrica', selecionado: false},
                {codigo: '625', descricao: 'Conta Petróleo', selecionado: false},
                {codigo: '631', descricao: 'Adequação de Rodovias', selecionado: false},
                {codigo: '632', descricao: 'Construção e Pavimentação Rodoviária', selecionado: false},
                {codigo: '633', descricao: 'Estudos e Pesquisas - DNIT', selecionado: false},
                {codigo: '634', descricao: 'Ferrovias - Pontos Críticos', selecionado: false},
                {codigo: '636', descricao: 'Hidrovias / Obras e Manutenção', selecionado: false},
                {codigo: '637', descricao: 'Manutenção da Malha Rodoviária Federal', selecionado: false},
                {codigo: '641', descricao: 'Apoio à Marinha Mercante', selecionado: false},
                {codigo: '645', descricao: 'Secretaria de Portos', selecionado: false},
                {codigo: '647', descricao: ' Portos (Obras, Modernização e Manutenção)', selecionado: false},
                {codigo: '649', descricao: 'Segurança nas Estradas / Controle de Velocidade', selecionado: false},
                {codigo: '650', descricao: 'Sistema de Pesagem de Veículos - Balanças', selecionado: false},
                {codigo: '661', descricao: 'Inclusão Digital', selecionado: false},
                {codigo: '662', descricao: 'ANATEL - Manutenção', selecionado: false},
                {codigo: '663', descricao: 'Funttel - Desenvolvimento Científico e Tecnológico', selecionado: false},
                {codigo: '665', descricao: 'FUST - Universalização dos Serviços de Telecomunicações', selecionado: false},
                {codigo: '680', descricao: 'Capitalização de Empresas', selecionado: false},
                {codigo: '691', descricao: 'Controle Ambiental', selecionado: false},
                {codigo: '692', descricao: 'Recursos Hídricos e Revitalização de Bacias Hidrográficas', selecionado: false},
                {codigo: '693', descricao: 'Preservação e Conservação do Meio Ambiente', selecionado: false},
                {codigo: '694', descricao: 'SFB - Sistema Florestal Brasileiro', selecionado: false},
                {codigo: '700', descricao: 'Desenvolvimento Sócio-Econômico Sustentável', selecionado: false},
                {codigo: '704', descricao: 'IBAMA - Demais', selecionado: false},
                {codigo: '705', descricao: 'ICMBio - Manutenção', selecionado: false},
                {codigo: '709', descricao: 'ANA - Manutenção', selecionado: false},
                {codigo: '720', descricao: 'Subsídios, Subvenções e Transferências', selecionado: false},
                {codigo: '721', descricao: 'Infraestrutura Hídrica', selecionado: false},
                {codigo: '722', descricao: 'Desenvolvimento Regional', selecionado: false},
                {codigo: '723', descricao: 'Defesa Civil', selecionado: false},
                {codigo: '724', descricao: 'Irrigação', selecionado: false},
                {codigo: '726', descricao: 'Drenagem', selecionado: false},
                {codigo: '727', descricao: 'São Francisco-Integração de Bacias', selecionado: false},
                {codigo: '728', descricao: 'São Francisco/Revitalização', selecionado: false},
                {codigo: '729', descricao: 'SUDAM', selecionado: false},
                {codigo: '730', descricao: 'SUDENE', selecionado: false},
                {codigo: '731', descricao: 'SUDECO', selecionado: false},
                {codigo: '753', descricao: 'Acessibilidade Universal', selecionado: false},
                {codigo: '754', descricao: 'Saneamento', selecionado: false},
                {codigo: '755', descricao: 'Habitação', selecionado: false},
                {codigo: '756', descricao: 'Gestão e Planejamento Urbanos', selecionado: false},
                {codigo: '758', descricao: 'Sistemas Ferroviários - Demais', selecionado: false},
                {codigo: '759', descricao: 'Mobilidade Urbana', selecionado: false},
                {codigo: '760', descricao: 'Extinção da Rede Ferroviária Federal S/A - RFFSA', selecionado: false},
                {codigo: '761', descricao: 'Segurança e Educação de Trânsito - DENATRAN/FUNSET', selecionado: false},
                {codigo: '762', descricao: 'Parceria Público-Privada - PPP', selecionado: false},
                {codigo: '763', descricao: 'Aeroportos', selecionado: false},
                {codigo: '764', descricao: 'Apoio Financeiro para Compensação das Exportações', selecionado: false},
                {codigo: '766', descricao: 'Missões Especiais', selecionado: false},
                {codigo: '767', descricao: 'Eclusas/Obras e Manutenção', selecionado: false},
                {codigo: '768', descricao: 'ANTT', selecionado: false},
                {codigo: '769', descricao: 'ANTAQ - Agência Nacional de Transportes Aquaviários', selecionado: false},
                {codigo: '780', descricao: 'FNDCT', selecionado: false},
                {codigo: '800', descricao: 'XXXXXXXXXXXXXXXXXXXXFIES', selecionado: false},
                {codigo: '802', descricao: 'Tecnologia da Informação', selecionado: false},
                {codigo: '811', descricao: 'Ampliação/Modernização/Reforma', selecionado: false},
                {codigo: '812', descricao: 'Aquisição de Imóveis', selecionado: false},
                {codigo: '813', descricao: 'Assistência Jurídica a Pessoas Carentes', selecionado: false},
                {codigo: '816', descricao: 'Capacitação de Recursos Humanos', selecionado: false},
                {codigo: '817', descricao: 'Comunicação Social', selecionado: false},
                {codigo: '818', descricao: 'Construção de Imóveis', selecionado: false},
                {codigo: '822', descricao: 'Implantação do e-Jus', selecionado: false},
                {codigo: '823', descricao: 'Fundo Partidário', selecionado: false},
                {codigo: '825', descricao: 'Implantação de Varas,  Ofícios, Procuradorias e Juizados Especiais', selecionado: false},
                {codigo: '827', descricao: 'Interlegis', selecionado: false},
                {codigo: '829', descricao: 'Outras Sentenças Judiciais', selecionado: false},
                {codigo: '830', descricao: 'Pessoal e Encargos Sociais', selecionado: false},
                {codigo: '831', descricao: 'Eleições', selecionado: false},
                {codigo: '832', descricao: 'Precatórios', selecionado: false},
                {codigo: '833', descricao: 'RPV', selecionado: false},
                {codigo: '839', descricao: 'Identificação Biométrica', selecionado: false},
                {codigo: '899', descricao: 'Demais Projetos', selecionado: false},
                {codigo: '901', descricao: 'Benefícios ao Servidor', selecionado: false},
                {codigo: '902', descricao: 'Capacitação de Público Externo', selecionado: false},
                {codigo: '903', descricao: 'Capacitação de Servidores', selecionado: false},
                {codigo: '905', descricao: 'Contribuições a Organismos e Entidades Nacionais e Internacionais', selecionado: false},
                {codigo: '906', descricao: 'Contribuições a Organismos Internacionais', selecionado: false},
                {codigo: '907', descricao: 'zDemais', selecionado: false},
                {codigo: '908', descricao: 'Reserva de Contingência', selecionado: false},
                {codigo: '909', descricao: 'Dívida', selecionado: false},
                {codigo: '911', descricao: 'Manutenção', selecionado: false},
                {codigo: '920', descricao: 'Obrigatórias / Financeiras', selecionado: false},
                {codigo: '921', descricao: 'Dívida Contratual Interna', selecionado: false},
                {codigo: '924', descricao: 'Recuperação Ambiental da Bacia Carbonífera do Estado de Santa Catarina', selecionado: false},
                {codigo: '925', descricao: 'Restauração do Palácio do Planalto', selecionado: false},
                {codigo: '926', descricao: 'Estudos e Pesquisas - VALEC', selecionado: false},
                {codigo: '927', descricao: 'Débitos Judiciais RFFSA', selecionado: false},
                {codigo: '928', descricao: 'Sentenças Judiciais - Justiça Estadual', selecionado: false},
                {codigo: 'FFF', descricao: 'Não Cadastrar Agregadores', selecionado: false},
                {codigo: 'P', descricao: '-', selecionado: false},
                {codigo: 'XXX', descricao: 'Pendente de Cadastramento', selecionado: false},
                {codigo: '001', descricao: 'Erradicação da Febre Aftosa', selecionado: false},
                {codigo: '002', descricao: 'Defesa Agropecuária (inclui LANAGROS e SUASA)', selecionado: false},
                {codigo: '003', descricao: 'Defesa Agropecuária (fiscalizações)', selecionado: false},
                {codigo: '004', descricao: 'Seguro Rural - Subvenção à Contratação de Seguro', selecionado: false},
                {codigo: '005', descricao: 'IBAMA - Manutenção', selecionado: false},
                {codigo: '006', descricao: ' EMBRAPA - Pesquisa Agropecuária', selecionado: false},
                {codigo: '007', descricao: ' CONAB - Abastecimento, Armazenagem e Comercialização', selecionado: false},
                {codigo: '008', descricao: 'Desenvolvimento da Cafeicultura (Funcafé)', selecionado: false},
                {codigo: '009', descricao: 'Anatel - Agência Nacional de Telecomunicações', selecionado: false},
                {codigo: '010', descricao: 'Estudos e Pesquisas - EPL', selecionado: false},
                {codigo: '011', descricao: 'ANP - Serviços de Geologia e Geofísica', selecionado: false},
                {codigo: '012', descricao: 'CPRM - Levantamentos Minerais', selecionado: false},
                {codigo: '013', descricao: 'EPE - Estudos Energéticos', selecionado: false},
                {codigo: '014', descricao: 'Modernização e Reformas', selecionado: false},
                {codigo: '015', descricao: 'Desenvolvimento das Regiões Cacaueiras (Ceplac)', selecionado: false},
                {codigo: '016', descricao: 'Promoção do Agronegócio no Mercado Internacional', selecionado: false},
                {codigo: '017', descricao: 'IBAMA - Combate ao Desmatamento', selecionado: false},
                {codigo: '018', descricao: 'Desenvolvimento das Cadeias Produtivas da Agropecuária', selecionado: false},
                {codigo: '019', descricao: 'IBAMA - Fiscalização e Combate ao Desmatamento', selecionado: false},
                {codigo: '020', descricao: 'ICMBio - Unidades de Conservação', selecionado: false},
                {codigo: '021', descricao: 'Meteorologia (Inmet)', selecionado: false},
                {codigo: '022', descricao: 'Despesas Administrativas da Adm. Direta', selecionado: false},
                {codigo: '023', descricao: ' CONAB - Ampliação/Reforma da Rede Armazenadora', selecionado: false},
                {codigo: '024', descricao: 'Ferrovia Norte-Sul', selecionado: false},
                {codigo: '025', descricao: 'Trem de Alta Velocidade - TAV', selecionado: false},
                {codigo: '026', descricao: 'ANA - Recursos Hídricos', selecionado: false},
                {codigo: '027', descricao: 'Metrô de Belo Horizonte', selecionado: false},
                {codigo: '028', descricao: 'Metrô de Salvador', selecionado: false},
                {codigo: '029', descricao: 'Metrô de Recife', selecionado: false},
                {codigo: '030', descricao: 'Metrô de Fortaleza', selecionado: false},
                {codigo: '031', descricao: 'Metrô de Porto Alegre', selecionado: false},
                {codigo: '032', descricao: 'Assentamentos Rurais', selecionado: false},
                {codigo: '033', descricao: 'Agricultura Familiar', selecionado: false},
                {codigo: '034', descricao: 'Garantia-Safra', selecionado: false},
                {codigo: '035', descricao: 'Programa de Aquisição de Alimentos - PAA', selecionado: false},
                {codigo: '036', descricao: 'Crédito Fundiário - Fundo de Terras', selecionado: false},
                {codigo: '037', descricao: 'Brasil Quilombola e Indígenas', selecionado: false},
                {codigo: '038', descricao: 'Educação no Campo - Pronera', selecionado: false},
                {codigo: '039', descricao: 'Obtenção de Imóveis para Reforma Agrária', selecionado: false},
                {codigo: '040', descricao: 'Assistência Técnica - ATER/ATES (Pronaf, Assentados, Quilombolas, Mulheres e Indígenas)', selecionado: false},
                {codigo: '041', descricao: 'Plano Safra da Pesca e Aquicultura', selecionado: false},
                {codigo: '042', descricao: 'TRENSURB - Funcionamento dos Sistemas Metroviários', selecionado: false},
                {codigo: '043', descricao: 'CBTU - Funcionamento dos Sistemas Metroviários', selecionado: false},
                {codigo: '044', descricao: 'Reaparelhamento Adm. Central - Projeto H-X BR', selecionado: false},
                {codigo: '045', descricao: 'Regularização de Estrutura Fundiária', selecionado: false},
                {codigo: '046', descricao: 'PREVIC', selecionado: false},
                {codigo: '047', descricao: 'FNMC', selecionado: false},
                {codigo: '048', descricao: 'Áreas de Risco', selecionado: false},
                {codigo: '049', descricao: 'Praças do PAC', selecionado: false},
                {codigo: '050', descricao: 'Transição de Governo', selecionado: false},
                {codigo: '051', descricao: 'Ferrovia Oeste-Leste', selecionado: false},
                {codigo: '052', descricao: 'Ferrovia de Integração do Centro-Oeste', selecionado: false},
                {codigo: '053', descricao: 'PUC Telebrás', selecionado: false},
                {codigo: '054', descricao: 'CNPq - Conselho Nacional de Desenvolvimento Científico e Tecnológico (exceto Bolsas)', selecionado: false},
                {codigo: '055', descricao: 'Desenvolvimento de Territórios Rurais', selecionado: false},
                {codigo: '056', descricao: 'PAC - Desenvolvimento de Territórios Rurais', selecionado: false},
                {codigo: '057', descricao: 'ExpoMilão 2015', selecionado: false},
                {codigo: '058', descricao: 'Recursos sob Supervisão da ANS', selecionado: false},
                {codigo: '059', descricao: 'Secretaria de Aviação Civil', selecionado: false},
                {codigo: '060', descricao: 'CBTU - Demais', selecionado: false},
                {codigo: '061', descricao: 'Metrologia e Qualidade Industrial', selecionado: false},
                {codigo: '062', descricao: 'Micro e Pequena Empresa', selecionado: false},
                {codigo: '063', descricao: 'Desenvolvimento Regional da Amazônia', selecionado: false},
                {codigo: '064', descricao: 'Propriedade Intelectual', selecionado: false},
                {codigo: '065', descricao: 'Comércio Exterior', selecionado: false},
                {codigo: '066', descricao: 'Desenvolvimento do Setor Produtivo', selecionado: false},
                {codigo: '067', descricao: 'Honra de Avais', selecionado: false},
                {codigo: '068', descricao: 'Mais Médicos', selecionado: false},
                {codigo: '069', descricao: 'PAC - Promoção do Turismo Interno', selecionado: false}
        ];
}
  

export function obterOpcoesAgregadores(){
        let opcoes = [];
        opcoes.push({value: null, text: "Selecione um agregador"});
        obterTodosAgregadores().forEach(agregador => opcoes.push({value: agregador.codigo, text: agregador.codigo + " - " + agregador.descricao}));
        return opcoes;
}
  